---
packageName: consul-wan-autojoin
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - [
      "@semantic-release/github",
      {
        "assets": [
          { "path": "consul-wan-autojoin", "label": "consul-wan-autojoin_linux_amd64" }
        ]
      }
  ]
  - "@semantic-release/release-notes-generator"
  - [
      "semantic-release-slack-bot",
      {
        "notifyOnSuccess": true,
        "notifyOnFail": true
      }
  ]
